version: "2.1"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    #volumes:
      #- ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 15s
      retries: 5

  testcrawler:
    image: testcrawler
    restart: always
    command: scrapy crawl product_spider -s RABBITMQ_HOST=amqp://guest:guest@rabbitmq:5672/ -s RABBITMQ_INPUT_QUEUE_KEY=scrapy_crawl_orders -s RABBITMQ_OUTPUT_QUEUE_KEY=scrapy_crawl_results
    depends_on:
      #for docker-compose
      #- rabbitmq
      #for docker compose
      rabbitmq:
        condition: service_healthy
